/**
 * Theme Library content — identical across Figma nodes 1550:3598 (Themes) and
 * 1550:5078 (Photoshoots); all 260 text nodes match between the two frames.
 * Only the photography for the first three cards and the active nav item differ,
 * so each route supplies its own image set via `imagesFor`.
 */
export const THEME_FILTERS = [
  "All",
  "Luxury",
  "Premium",
  "Outdoor",
  "Studio",
  "Birthday",
  "Maternity",
  "Family",
];

export const THEMES = [
  {
    slug: "royal-boho",
    name: "Royal Boho",
    category: "Maternity",
    price: "₹6,499",
    rating: "4.9",
    popularity: "94% popularity",
    viewing: "13 viewing",
    trending: true,
    hotCity: "#18 booked in Bangalore this week",
    photos: "6 photos",
    props: ["Floral Arch", "Boho Baskets", "Macramé"],
    gowns: ["Sage Green Drape", "Cream Lace"],
    viewingNow: "13 viewing now",
    bookingThisWeek: "10 booking this week",
    bookedThisWeek: "18 booked this week",
    hotIn: "Hot in Bangalore",
    lastBooked: "Last booked 2 hrs ago · 74 this month",
  },
  {
    slug: "luxury-newborn",
    name: "Luxury Newborn",
    category: "Newborn",
    price: "₹7,999",
    rating: "4.9",
    popularity: "87% popularity",
    viewing: "8 viewing",
    trending: false,
    hotCity: "#13 booked in Mumbai this week",
    photos: "6 photos",
    props: ["Wicker Basket", "Fur Wraps", "Floral Halo"],
    gowns: ["Ivory Wrap"],
    viewingNow: "8 viewing now",
    bookingThisWeek: "8 booking this week",
    bookedThisWeek: "13 booked this week",
    hotIn: "Hot in Mumbai",
    lastBooked: "Last booked 3 hrs ago · 51 this month",
  },
  {
    slug: "princess-birthday",
    name: "Princess Birthday",
    category: "Birthday",
    price: "₹8,999",
    rating: "5",
    popularity: "98% popularity",
    viewing: "16 viewing",
    trending: true,
    hotCity: "#26 booked in Bangalore this week",
    photos: "6 photos",
    props: ["Gold Throne", "Balloon Arc", "Crown"],
    gowns: ["Pink Tutu", "Gold Gown"],
    viewingNow: "16 viewing now",
    bookingThisWeek: "14 booking this week",
    bookedThisWeek: "26 booked this week",
    hotIn: "Hot in Bangalore",
    lastBooked: "Last booked 45 min ago · 104 this month",
  },
  {
    slug: "family-garden",
    name: "Family Garden",
    category: "Family",
    price: "₹9,999",
    rating: "5",
    popularity: "91% popularity",
    viewing: "12 viewing",
    trending: true,
    hotCity: "#16 booked in Hyderabad this week",
    photos: "6 photos",
    props: ["Picnic Setup", "Floral Wreath", "Blanket"],
    gowns: ["Matching Pastels"],
    viewingNow: "12 viewing now",
    bookingThisWeek: "9 booking this week",
    bookedThisWeek: "16 booked this week",
    hotIn: "Hot in Hyderabad",
    lastBooked: "Last booked 2 hrs ago · 63 this month",
  },
  {
    slug: "beach-pre-wedding",
    name: "Beach Pre-Wedding",
    category: "Pre-Wedding",
    price: "₹16,999",
    rating: "4.8",
    popularity: "82% popularity",
    viewing: "7 viewing",
    trending: false,
    hotCity: "#11 booked in Mumbai this week",
    photos: "6 photos",
    props: ["Fairy Lights", "Boat", "Flower Petals"],
    gowns: ["White Gown", "Floral Lehenga"],
    viewingNow: "7 viewing now",
    bookingThisWeek: "7 booking this week",
    bookedThisWeek: "11 booked this week",
    hotIn: "Hot in Mumbai",
    lastBooked: "Last booked 5 hrs ago · 44 this month",
  },
  {
    slug: "classic-white",
    name: "Classic White",
    category: "Wedding",
    price: "₹24,999",
    rating: "4.9",
    popularity: "76% popularity",
    viewing: "11 viewing",
    trending: false,
    hotCity: "#13 booked in Mumbai this week",
    photos: "6 photos",
    props: ["Arch", "Candles", "Floral Wall"],
    gowns: ["Ivory Bridal Gown"],
    viewingNow: "11 viewing now",
    bookingThisWeek: "7 booking this week",
    bookedThisWeek: "13 booked this week",
    hotIn: "Hot in Mumbai",
    lastBooked: "Last booked 3 hrs ago · 52 this month",
  },
  {
    slug: "studio-minimal",
    name: "Studio Minimal",
    category: "Couple",
    price: "₹8,999",
    rating: "4.8",
    popularity: "71% popularity",
    viewing: "6 viewing",
    trending: false,
    hotCity: "#9 booked in Bangalore this week",
    photos: "6 photos",
    props: ["Neon Signs", "Chair", "Ladder"],
    gowns: ["Matching Coords"],
    viewingNow: "6 viewing now",
    bookingThisWeek: "5 booking this week",
    bookedThisWeek: "9 booked this week",
    hotIn: "Hot in Bangalore",
    lastBooked: "Last booked 7 hrs ago · 36 this month",
  },
  {
    slug: "sunlit-maternity",
    name: "Sunlit Maternity",
    category: "Maternity",
    price: "₹5,999",
    rating: "4.8",
    popularity: "85% popularity",
    viewing: "11 viewing",
    trending: false,
    hotCity: "#14 booked in Chennai this week",
    photos: "6 photos",
    props: ["Sheer Panels", "Window Light", "Flowers"],
    gowns: ["Blush Wrap Gown"],
    viewingNow: "11 viewing now",
    bookingThisWeek: "7 booking this week",
    bookedThisWeek: "14 booked this week",
    hotIn: "Hot in Chennai",
    lastBooked: "Last booked 4 hrs ago · 56 this month",
  },
  {
    slug: "golden-hour-family",
    name: "Golden Hour Family",
    category: "Family",
    price: "₹9,499",
    rating: "4.9",
    popularity: "89% popularity",
    viewing: "13 viewing",
    trending: true,
    hotCity: "#19 booked in Bangalore this week",
    photos: "6 photos",
    props: ["Lanterns", "Blankets", "Wooden Frame"],
    gowns: ["Earth Tones"],
    viewingNow: "13 viewing now",
    bookingThisWeek: "10 booking this week",
    bookedThisWeek: "19 booked this week",
    hotIn: "Hot in Bangalore",
    lastBooked: "Last booked 2 hrs ago · 77 this month",
  },
];

const themeImages = import.meta.glob("./assets/themes/*.jpg", {
  eager: true,
  import: "default",
});
const photoshootImages = import.meta.glob("./assets/photoshoots/*.jpg", {
  eager: true,
  import: "default",
});

export function imagesFor(variant) {
  const set = variant === "photoshoots" ? photoshootImages : themeImages;
  return Object.fromEntries(
    Object.entries(set).map(([path, url]) => [
      path.split("/").pop().replace(".jpg", ""),
      url,
    ])
  );
}
